org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError

android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

# Disable incremental compilation to prevent cache lock / corruption issues on Windows
kotlin.incremental=false
https://127.0.0.1:49522/static/artifacts/f9fd90f9-488e-4f58-8dfb-f35834cdd363/.user_uploaded/media_1789293840635.png?csrf=21868c65-d601-497e-9390-bbff507ff786